import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import MySessionPrividers from "@/providers/MySessionPrividers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

{/* used session provider to use session {to get the token} */}


<MySessionPrividers>
        <Toaster />
        <Navbar/>
        <div className="conatiner max-w-7xl mx-auto">
        {children}
        </div>
</MySessionPrividers>

      </body>
    </html>
  );
}
